services:

  devcontainer:
    build:
      target: dev
    volumes:
      - ..:/workspaces
      - command-history-volume:/home/user/.history/

  app:
    build:
      target: app
    ports:
      - "8000:8000"
    profiles:
      - app

volumes:
  command-history-volume:
