---
name: ship and deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"
      - "*.*.*"
    paths-ignore:
      - .github/**

# Prevent concurrent builds on the same SHA for the repo
concurrency:
  group: ${{ github.repository }}-${{ github.sha }}

env:
  ENVIRONMENT: null

jobs:
  environment:
    runs-on: ["agents-runners"]
    outputs:
      target: ${{ env.ENVIRONMENT }}
    steps:
      - name: set env to strg-integration
        if: ${{ startsWith(github.ref, 'refs/heads/main') }}
        run: |
          echo "ENVIRONMENT=strg-integration" >> $GITHUB_ENV
      - name: set env to release-candidate
        if: ${{ startsWith(github.ref, 'refs/tags/') && (contains(github.ref, '-rc') || contains(github.ref, 'v0.')) }}
        run: |
          echo "ENVIRONMENT=release-candidate" >> $GITHUB_ENV
      - name: set env to production
        if: ${{ startsWith(github.ref, 'refs/tags/') && !contains(github.ref, '-rc') && !contains(github.ref, 'v0.') }}
        run: |
          echo "ENVIRONMENT=production" >> $GITHUB_ENV

  check-image-exists:
    uses: "strg-at/github-workflows/.github/workflows/docker-image-exists-google.yaml@fe8aec8df10849c97cc87d1d2e1448d03121aceb"
    with:
      runner: '["agents-runners"]'
      workload-identity-provider: "projects/585630107782/locations/global/workloadIdentityPools/github/providers/github-oidc-provider"
      service-account: "github-artifactregistry@logical-sled-220910.iam.gserviceaccount.com"
      registry: "europe-west3-docker.pkg.dev"
      gcp: "logical-sled-220910"
      repository: "strg-docker"
      subpath: "behave-collaborative-filtering-service"

  docker-build-push:
    needs: [check-image-exists]
    if: ${{ needs.check-image-exists.outputs.tag == 'not found' }}
    name: "docker build"
    uses: "strg-at/github-workflows/.github/workflows/docker-build-push-google.yaml@fe8aec8df10849c97cc87d1d2e1448d03121aceb"
    with:
      runner: '["agents-runners"]'
      workload-identity-provider: "projects/585630107782/locations/global/workloadIdentityPools/github/providers/github-oidc-provider"
      service-account: "github-artifactregistry@logical-sled-220910.iam.gserviceaccount.com"
      registry: "europe-west3-docker.pkg.dev"
      gcp: "logical-sled-220910"
      repository: "strg-docker"
      subpath: "behave-collaborative-filtering-service"
      tags: |
        type=ref,event=tag,priority=300
        type=sha,prefix={{date 'YYMMDD-HHmmss'}}-,priority=200
        ${{ github.sha }}, priority=100

  tag-image-google:
    needs: [check-image-exists]
    if: ${{ needs.check-image-exists.outputs.tag == 'found' }}
    name: "retag image"
    uses: "strg-at/github-workflows/.github/workflows/tag-image-google.yaml@fe8aec8df10849c97cc87d1d2e1448d03121aceb"
    with:
      runner: '["agents-runners"]'
      workload-identity-provider: "projects/585630107782/locations/global/workloadIdentityPools/github/providers/github-oidc-provider"
      service-account: "github-artifactregistry@logical-sled-220910.iam.gserviceaccount.com"
      registry: "europe-west3-docker.pkg.dev"
      gcp: "logical-sled-220910"
      repository: "strg-docker"
      source-path: "behave-collaborative-filtering-service"
      target-path: "behave-collaborative-filtering-service"

  integration-dispatch:
    needs: [environment, docker-build-push, tag-image-google]
    if: ${{ always() && (needs.docker-build-push.result == 'success' || needs.tag-image-google.result == 'success') && needs.environment.outputs.target == 'strg-integration' }}
    name: ${{ needs.environment.outputs.target }}
    uses: "strg-at/github-workflows/.github/workflows/repo-dispatch.yaml@fe8aec8df10849c97cc87d1d2e1448d03121aceb"
    with:
      runner: '["agents-runners"]'
      tag: ${{ github.sha }}
      repository: "strg-at/agents-flux-cluster"
      dispatch-event: ${{ needs.environment.outputs.target }}-behave-collaborative-filtering-service-tag-update
    secrets:
      github-app-id: ${{ secrets.STRG_BOT_GITHUB_APP_ID }}
      github-app-key: ${{ secrets.STRG_BOT_GITHUB_PEM }}

  production-dispatch:
    needs: [environment, docker-build-push, tag-image-google]
    if: ${{ always() && (needs.docker-build-push.result == 'success' || needs.tag-image-google.result == 'success') && needs.environment.outputs.target == 'production' }}
    name: ${{ needs.environment.outputs.target }}
    uses: "strg-at/github-workflows/.github/workflows/repo-dispatch.yaml@fe8aec8df10849c97cc87d1d2e1448d03121aceb"
    with:
      runner: '["agents-runners"]'
      tag: ${{ github.ref_name }}
      repository: "strg-at/dav-flux-cluster"
      dispatch-event: ${{ needs.environment.outputs.target }}-daz-behave-collaborative-filtering-service-tag-update
    secrets:
      github-app-id: ${{ secrets.STRG_BOT_GITHUB_APP_ID }}
      github-app-key: ${{ secrets.STRG_BOT_GITHUB_PEM }}
